language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
      
    - python: 3.4
      dist: trusty

    - python: 3.5
      dist: trusty

    - python: 3.6
      dist: trusty

    - python: 3.7
      dist: xenial
      sudo: true

    - python: nightly
      dist: xenial

  allow_failures:
    - python: "nightly"

install:
  - python setup.py install

script:
  - python tests/run_tests.py